helloworld/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    # Inclui as URLs do app ‘website’
    path('', include('myapp.urls', namespace='myapp')),

    # Interface administrativa
    path('admin/', admin.site.urls),
]

myapp/urls.py
from myapp.views import IndexTemplateView, FuncionarioListView, FuncionarioUpdateView, FuncionarioCreateView, \
    FuncionarioDeleteView

from django.urls import path

app_name = 'myapp'

urlpatterns = [
    # GET /
    path('', IndexTemplateView.as_view(), name="index"),

    # GET /funcionario/cadastrar
    path('funcionario/cadastrar', FuncionarioCreateView.as_view(), name="cadastra_funcionario"),

    # GET /funcionarios
    path('funcionarios/', FuncionarioListView.as_view(), name="lista_funcionarios"),

    # GET/POST /funcionario/{pk}
    path('funcionario/<pk>', FuncionarioUpdateView.as_view(), name="atualiza_funcionario"),

    # GET/POST /funcionarios/excluir/{pk}
    path('funcionario/excluir/<pk>', FuncionarioDeleteView.as_view(), name="deleta_funcionario"),
]

helloworld/models.py
from django.db import models

# Create your models here.

class Funcionario(models.Model):

    nome = models.CharField(max_length=250, null=False, blank=False)

    sobrenome = models.CharField(max_length=250, null=False, blank=False)

    bilhete = models.CharField(max_length=14, null=False, blank=False)

    tempo_de_servico = models.IntegerField(default=0, null=False, blank=False)

    salario = models.DecimalField(max_digits=8, decimal_places=2, null=False, blank=False)

    objetos = models.Manager()

myapp/forms.py
from helloworld.models import Funcionario
from django import forms


# FORMULÁRIO DE INCLUSÃO DE FUNCIONÁRIOS
# -------------------------------------------

class InsereFuncionarioForm(forms.ModelForm):

    chefe = forms.BooleanField(
        label='Chefe?',
        required=False,
    )

    biografia = forms.CharField(
        label='Biografia',
        required=False,
        widget=forms.Textarea
    )

    class Meta:
        # Modelo base
        model = Funcionario

        # Campos que estarão no form
        fields = [
            'nome',
            'sobrenome',
            'bilhete',
            'tempo_de_servico',
            'salario'
        ]

myapp/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from helloworld.models import Funcionario
from myapp.forms import InsereFuncionarioForm


# PÁGINA PRINCIPAL
# ----------------------------------------------

class IndexTemplateView(TemplateView):
    template_name = "myapp/index.html"


# LISTA DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioListView(ListView):
    template_name = "myapp/lista.html"
    model = Funcionario
    context_object_name = "funcionarios"


# CADASTRAMENTO DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioCreateView(CreateView):
    template_name = "myapp/cria.html"
    model = Funcionario
    form_class = InsereFuncionarioForm
    success_url = reverse_lazy("myapp:lista_funcionarios")


# ATUALIZAÇÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioUpdateView(UpdateView):
    template_name = "myapp/atualiza.html"
    model = Funcionario
    fields = '__all__'
    context_object_name = 'funcionario'
    success_url = reverse_lazy("myapp:lista_funcionarios")


# EXCLUSÃO DE FUNCIONÁRIOS
# ----------------------------------------------

class FuncionarioDeleteView(DeleteView):
    template_name = "myapp/exclui.html"
    model = Funcionario
    context_object_name = 'funcionario'
    success_url = reverse_lazy("myapp:lista_funcionarios")
from django.shortcuts import render

# Create your views here.

myapp/templates/myapp/_layouts/base.html
<!DOCTYPE html>
<html>
    {% load static tempo_atual %}

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Title -->
        <title>{% block title %}Sistema de Gerenciamento de Funcionários{% endblock %}</title>

        <!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'myapp/img/python.png' %}" type="image/png">

        <!-- Arquivos CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/css/master.css' %}">

        {% block styles %}{% endblock %}
    </head>

    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'myapp:index' %}">
              <img src="{% static 'myapp/img/python.png' %}" height="45px">
            </a>
            <button class="navbar-toggler" type="button" 
                data-toggle="collapse" data-target="#navbarSupportedContent" 
                aria-controls="navbarSupportedContent" aria-expanded="false" 
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'myapp:index' %}">Página Inicial</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:lista_funcionarios' %}">Funcionários</a>
                    </li>
                </ul>
                <ul class="navbar-nav float-right">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><b>Hora: </b>{% tempo_atual %}</a>
                    </li>
                </ul>
            </div>
        </nav>
        
        <!-- Conteúdo do site -->
        {% block conteudo %}{% endblock %}

        <!-- Scripts .js -->
        <script src="{% static 'myapp/js/jquery.min.js' %}"></script>
        <script src="{% static 'myapp/js/bootstrap.min.js' %}"></script>

        {% block scripts %}{% endblock %}

        <script src="{% static 'myapp/js/scripts.js' %}"></script>
    </body>
</html>

myapp/templates/myapp/atualiza.html
{% extends "myapp/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Funcionário{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Dados de Funcionário</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.nome class+="form-control" %}
            </div>

            <!-- Sobrenome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Sobrenome</span>
              </div>
              {% render_field form.sobrenome class+="form-control" %}
            </div>

            <!-- Bilhete -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Bilhete</span>
              </div>
              {% render_field form.bilhete class+="form-control" %}
            </div>

            <!-- Tempo de Serviço -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Tempo de Serviço</span>
              </div>
              {% render_field form.tempo_de_servico class+="form-control" %}
            </div>

            <!-- Salário -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Salário</span>
              </div>
              {% render_field form.salario class+="form-control" %}
            </div>
            <hr />
            <div class="text-right">
              <a href="{% url 'myapp:lista_funcionarios' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

myapp/templates/myapp/cria.html
{% extends "myapp/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Cadastro de Funcionários{% endblock %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastro de Funcionário</h5>
          <p class="card-text">
            Complete o formulário abaixo para cadastrar
            um novo <code>Funcionário</code>.
          </p>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.nome class+="form-control" %}
            </div>

            <!-- Sobrenome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Sobrenome</span>
              </div>
              {% render_field form.sobrenome class+="form-control" %}
            </div>

            <!-- Bilhete -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Bilhete</span>
              </div>
              {% render_field form.bilhete class+="form-control" %}
            </div>

            <!-- Tempo de Serviço -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Tempo de Serviço</span>
              </div>
              {% render_field form.tempo_de_servico class+="form-control" %}
            </div>

            <!-- Salário -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Salário</span>
              </div>
              {% render_field form.salario class+="form-control" %}
            </div>
            <hr>
            <div class="text-right">
              <a href="{% url 'myapp:lista_funcionarios' %}" class="btn btn-outline-primary">Voltar</a>
              <button class="btn btn-primary">Enviar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

myapp/templates/myapp/exclui.html
<!-- Estendemos do template base -->
{% extends "myapp/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Funcionário</h5>

        <p class="card-text">
          Você tem certeza que quer excluir o funcionário <b>{{ funcionario.nome }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'myapp:lista_funcionarios' %}" class="btn btn-outline-danger">
              Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

myapp/templates/myapp/index.html
<!-- Estendemos do template base -->
{% extends "myapp/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastrar Funcionário</h5>
          <p class="card-text">
            Cadastre aqui um novo <code>Funcionário</code>.
          </p>
          <a href="{% url 'myapp:cadastra_funcionario' %}"
             class="btn btn-primary">
            Novo Funcionário
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Funcionários</h5>
          <p class="card-text">
            Veja aqui a lista de <code>Funcionários</code> cadastrados.
          </p>
          <a href="{% url 'myapp:lista_funcionarios' %}"
             class="btn btn-primary">
            Vá para Lista
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

myapp/templates/myapp/lista.html
{% extends "myapp/_layouts/base.html" %}

{% block title %}Lista de Funcionários{% endblock %}

{% load primeira_letra %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Funcionário</h5>

          {% if funcionarios|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Funcionários</code> cadastrados.
            </p>

            <table class="table">
              <thead class="thead-dark">
              <tr>
                <th scope="col"></th>
                <th scope="col">Nome</th>
                <th scope="col">Sobrenome</th>
                <th scope="col">Tempo de Serviço</th>
                <th scope="col">Salário</th>
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for funcionario in funcionarios %}
                <tr>
                  <th scope="row">{{ funcionario.nome|primeira_letra }}</th>
                  <td>{{ funcionario.nome }}</td>
                  <td>{{ funcionario.sobrenome }}</td>
                  <td>{{ funcionario.tempo_de_servico }}</td>
                  <td>{{ funcionario.salario }}</td>
                  <td class="text-center">
                    <a href="{% url 'myapp:atualiza_funcionario' pk=funcionario.id %}"
                       class="btn btn-primary">
                      Atualizar
                    </a>
                    <a href="{% url 'myapp:deleta_funcionario' pk=funcionario.id %}"
                      class="btn btn-danger">
                        Excluir
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Funcionário</code> cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'myapp:cadastra_funcionario' %}" class="btn btn-primary">
              Cadastrar Funcionário
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}